text_model_lora_config:
  r: 64  # no/little change in the range [16, 64]
  target_modules: ['mlp.gate_proj', 'mlp.up_proj', 'mlp.down_proj', 'v_proj', 'o_proj', 'k_proj', 'q_proj']

data_sets: ["commonvoice", "peoplespeech", "anyinstruct"]

# disable_layer_drop: True
# audio_model_lora_config:
#   r: 64
#   target_modules: ['k_proj', 'q_proj', 'v_proj', 'out_proj', 'intermediate_dense', 'output_dense']

num_prompts: 6

lr: 1.e-4  # need a lower LR for LLM fine-tuning
lr_warmup_steps: 250
max_steps: 5_000
